[package]
name = "itest"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]
# Do not add features here that are 1:1 forwarded to the `godot` crate.
# Instead, compile itest with `--features godot/my-feature`.

[dependencies]
godot = { path = "../../godot", default-features = false }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
godot-bindings = { path = "../../godot-bindings" } # emit_godot_version_cfg
# Minimum versions compatible with -Zminimal-versions
proc-macro2 = "1.0.63"
quote = "1.0.29"

